### PR TITLE
Update document.php

### PR DESCRIPTION
**Pull request by sheetalbalpathak**
Fixed notice undefined index while doing dataArray()

@treehousetim please review and let me know.

### CODE REVIEW

**Review by treehousetim — CHANGES_REQUESTED** [review]
Please refactor.

**Comment by sheetalbalpathak** [comment]
Refactor the code. Please check

**Comment by sheetalbalpathak** [comment]
Fixed blank array issue and undefined index notice issue

**Review by treehousetim — APPROVED** [review]

**Comment by treehousetim** [comment]
Thank you for the PR - the changes have been accepted and merged.

**Pull request merged**
